name: Build .deb Packages

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/**"
      - "build-deb.sh"

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: tag-${{ github.sha }}
          release_name: ${{ github.sha }}
          draft: false
          prerelease: true

  build:
    runs-on: ubuntu-latest
    needs: create_release
    strategy:
      matrix:
        dockerfile:
          [
            "ubuntu:latest",
            "ubuntu:rolling",
            "debian:stable",
            "debian:testing",
            "balenalib/raspberrypi3-debian:buster",
            "balenalib/raspberrypi3-debian:stretch",
            "balenalib/aarch64-ubuntu:latest",
          ]
        include:
          - dockerfile: "ubuntu:latest"
            name: Ubuntu LTS
          - dockerfile: "ubuntu:rolling"
            name: Ubuntu Latest
          - dockerfile: "debian:stable"
            name: Debian Stable
          - dockerfile: "debian:testing"
            name: Debian Testing
          - dockerfile: "balenalib/raspberrypi3-debian:buster"
            name: Raspbian Buster
          - dockerfile: "balenalib/raspberrypi3-debian:stretch"
            name: Raspbian Stretch
          - dockerfile: "balenalib/aarch64-ubuntu:latest"
            name: Ubuntu LTS arm64
    steps:
      - name: Install qemu
        run: sudo apt-get update && sudo apt install -y qemu-user-static  binfmt-support --no-install-recommends
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Build the Package
        run: |
          cat ./build-deb.sh | docker run --name=build -i ${{ matrix.dockerfile }} /bin/sh
          docker cp build:/root/webthings-gateway.deb ./webthings-gateway.deb
          - name: Upload binaries to release
      - name: Upload Release
        uses: "svenstaro/upload-release-action@v1-release"
        with:
          repo_token: ${{ secrets.RELEASE_TOKEN }}
          file: ./webthings-gateway.deb
          asset_name: webthings-gateway-${{ matrix.name }}.deb
          tag: tag-${{ github.sha }}
